{
 "title": "Service Details > DB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_labels,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_name=\"$cluster\"},k8s_namespace_name)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_name=\"$cluster\", k8s_namespace_name=\"$namespace\"},label_app_kubernetes_io_name)"
    }
   },
   {
    "name": "display_jvm",
    "query": {
     "query": "query_result(label_replace(  sum({    __name__=\"jvm_class_count\",    k8s_cluster_name=\"$cluster\",    k8s_namespace_name=\"$namespace\",    service_name=\"$service\"  }),  \"display_jvm\", \"block\", \"\", \"\") or label_replace(  absent({    __name__=\"jvm_class_count\",    k8s_cluster_name=\"$cluster\",    k8s_namespace_name=\"$namespace\",    service_name=\"$service\"  }),  \"display_jvm\", \"none\", \"\", \"\"))"
    }
   },
   {
    "name": "display_python",
    "query": {
     "query": "query_result(label_replace(  sum({    __name__=\"cpython_gc_collections_total\",    k8s_cluster_name=\"$cluster\",    k8s_namespace_name=\"$namespace\",    service_name=\"$service\"  }),  \"display_python\", \"block\", \"\", \"\") or label_replace(  absent({    __name__=\"cpython_gc_collections_total\",    k8s_cluster_name=\"$cluster\",    k8s_namespace_name=\"$namespace\",    service_name=\"$service\"  }),  \"display_python\", \"none\", \"\", \"\"))"
    }
   },
   {
    "name": "display_nodejs",
    "query": {
     "query": "query_result(label_replace(  sum({    __name__=\"nodejs_eventloop_utilization_ratio\",    k8s_cluster_name=\"$cluster\",    k8s_namespace_name=\"$namespace\",    service_name=\"$service\"  }),  \"display_nodejs\", \"block\", \"\", \"\") or label_replace(  absent({    __name__=\"nodejs_eventloop_utilization_ratio\",    k8s_cluster_name=\"$cluster\",    k8s_namespace_name=\"$namespace\",    service_name=\"$service\"  }),  \"display_nodejs\", \"none\", \"\", \"\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n  <h1>Services: ${service}</h1>\n  <div style=\"display:flex; gap:8px; border-bottom: 1px solid #333;\">\n    <a href=\"/d/svc-overview?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:white; text-decoration:none; border-bottom: 1px solid #ff8833;\">\n        Overview\n    </a>\n    <a href=\"/d/svc-metric?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Metrics\n    </a>\n    <a href=\"/d/svc-log?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Logs\n    </a>                                                                            \n        <a href=\"/d/svc-trace-http?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        HTTP\n    </a>\n    <a href=\"/d/svc-trace-db?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:white; text-decoration:none; border-bottom: 1px solid #ff8833;\">\n        DB\n    </a>\n    <a href=\"/d/svc-trace-messaging?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Messaging\n    </a>\n    <a href=\"/d/svc-metric-jvm?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none; display: ${display_jvm};\">\n        JVM\n    </a>\n    <a href=\"/d/svc-metric-python?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none; display: ${display_python};\">\n        Python\n    </a>\n    <a href=\"/d/svc-metric-nodejs?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none; display: ${display_nodejs};\">\n        NodeJS\n    </a>\n  </div>\n</div>"
   }
  },
  {
   "title": "Connection 사용량",
   "type": "bargauge",
   "description": "Used, Idle, Max",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_client_connections_usage {\n  service_name=\"$service\",\n  state=\"used\"\n})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(db_client_connections_usage {\n  service_name=\"$service\",\n  state=\"idle\"\n})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(db_client_connections_max {\n  service_name=\"$service\"\n})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "DB 쿼리 추적",
   "type": "table",
   "description": "DB 쿼리 추적",
   "gridPos": { "h": 19, "w": 19, "x": 5, "y": 3 },
   "targets": [
    {
     "filters": [
      {
       "id": "40e83fc2",
       "isCustomValue": false,
       "operator": "=~",
       "scope": "span",
       "tag": "http.request.method",
       "value": [ "$http_method" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service" ],
       "valueType": "string"
      },
      {
       "id": "3436a1be",
       "isCustomValue": false,
       "operator": "=~",
       "scope": "span",
       "tag": "http.route",
       "value": [ "$http_url" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": [ "GET /actuator/health" ],
       "valueType": "string"
      }
     ],
     "limit": 2000,
     "metricsQueryType": "range",
     "query": "{\n  resource.service.name=\"$service\"\n  && span:name!=\"\"\n  && (span.db.system=~\".+\" || span.db.operation=~\".+\" || span.db.sql.table=~\".+\" || span.db.statement=~\".+\")\n  && (span.db.statement!=\"INFO server\")\n}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Connection 대기 건수",
   "type": "stat",
   "description": "유휴 Connection 없어 대기중인 건수",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_client_connections_pending_requests {\n  service_name=\"$service\"\n})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Avg Hold Time",
   "type": "timeseries",
   "description": "Connection 사용-반환 평균시간",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(\n  db_client_connections_use_time_milliseconds_sum{\n    service_name=\"$service\"\n  }[5m]\n)\n/\nrate(\n  db_client_connections_use_time_milliseconds_count{\n    service_name=\"$service\"\n  }[5m]\n)",
     "legendFormat": "Connection 사용-반환 평균시간"
    }
   ]
  },
  {
   "title": "Hold Time (p95)",
   "type": "timeseries",
   "description": "Connection 사용-반환 시간(p95)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  rate(\n    db_client_connections_use_time_milliseconds_bucket{\n      service_name=\"$service\"\n    }[5m]\n  )\n)",
     "legendFormat": "Connection 사용-반환 시간"
    }
   ]
  }
 ]
}