{
 "title": "Service Details > Python",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_labels,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_name=\"$cluster\"},k8s_namespace_name)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "query_result(sum by (service_name)(  label_replace(    kube_pod_labels {      label_app_kubernetes_io_name!=\"\",      k8s_cluster_name=\"$cluster\",      k8s_namespace_name=\"$namespace\"    },    \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.+)\"     )))"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(sum by (k8s_pod_name, k8s_namespace_name, k8s_cluster_uid)(  kube_pod_info {    k8s_pod_name!=\"\",    k8s_namespace_name=\"$namespace\",    k8s_cluster_name=\"$cluster\"  })* on(k8s_pod_name) group_left(pod) kube_pod_labels {  label_app_kubernetes_io_name=\"$service\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n  <h1>Services</h1>\n  <div style=\"display:flex; gap:8px; border-bottom: 1px solid #333;\">\n    <a href=\"/d/svc-overview?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Overview\n    </a>\n    <a href=\"/d/svc-metric?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Metrics\n    </a>\n    <a href=\"/d/svc-log?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Logs\n    </a>                                                                            \n    <a href=\"/d/svc-trace?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Traces\n    </a>\n    <a href=\"/d/svc-trace-http?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        HTTP\n    </a>\n    <a href=\"/d/svc-trace-db?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        DB\n    </a>\n    <a href=\"/d/svc-trace-messaging?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Messaging\n    </a>\n    <a href=\"/d/svc-metric-jvm?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        JVM\n    </a>\n    <a href=\"/d/svc-metric-python?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:white; text-decoration:none; border-bottom: 1px solid #ff8833;\">\n        Python\n    </a>\n    <a href=\"/d/svc-metric-nodejs?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        NodeJS\n    </a>\n  </div>\n</div>"
   }
  },
  {
   "title": "Total Async Processes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({\n    __name__=\"asyncio_process_duration_seconds_count\",\n    service_name=\"$service\"}\n)"
    }
   ]
  },
  {
   "title": "AsyncIO Processes",
   "type": "table",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "{\n    __name__=\"asyncio_process_duration_seconds_count\",\n    service_name=\"$service\"\n}"
    }
   ]
  },
  {
   "title": "GC Runs/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "targets": [
    {
     "expr": "rate({\n    __name__=\"cpython_gc_collections_total\",\n    generation=\"0\",\n    service_name=\"$service\"\n}[$__rate_interval])",
     "legendFormat": "Generation 0"
    },
    {
     "expr": "rate({\n    __name__=\"cpython_gc_collections_total\",\n    generation=\"1\",\n    service_name=\"$service\"\n}[$__rate_interval])",
     "legendFormat": "Generation 1"
    },
    {
     "expr": "rate({\n    __name__=\"cpython_gc_collections_total\",\n    generation=\"0\",\n    service_name=\"$service\"\n}[$__rate_interval])",
     "legendFormat": "Generation 2"
    }
   ]
  },
  {
   "title": "GC Collected Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({\n    __name__=\"cpython_gc_collected_objects_total\",\n    generation=\"0\",\n    service_name=\"$service\"\n}[$__rate_interval])",
     "legendFormat": "Generation 0"
    },
    {
     "expr": "rate({\n    __name__=\"cpython_gc_collected_objects_total\",\n    generation=\"1\",\n    service_name=\"$service\"\n}[$__rate_interval])",
     "legendFormat": "Generation 1"
    },
    {
     "expr": "rate({\n    __name__=\"cpython_gc_collected_objects_total\",\n    generation=\"0\",\n    service_name=\"$service\"\n}[$__rate_interval])",
     "legendFormat": "Generation 2"
    }
   ]
  },
  {
   "title": "Uncollectable Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({\n    __name__=\"cpython_gc_uncollectable_objects_total\",\n    generation=\"0\",\n    service_name=\"$service\"\n}[$__rate_interval])",
     "legendFormat": "Generation 0"
    },
    {
     "expr": "rate({\n    __name__=\"cpython_gc_uncollectable_objects_total\",\n    generation=\"1\",\n    service_name=\"$service\"\n}[$__rate_interval])",
     "legendFormat": "Generation 1"
    },
    {
     "expr": "rate({\n    __name__=\"cpython_gc_uncollectable_objects_total\",\n    generation=\"0\",\n    service_name=\"$service\"\n}[$__rate_interval])",
     "legendFormat": "Generation 2"
    }
   ]
  }
 ]
}