{
 "title": "Service Details > Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_labels,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_name=\"$cluster\"},k8s_namespace_name)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "query_result(sum by (service_name)(  label_replace(    kube_pod_labels {      label_app_kubernetes_io_name!=\"\",      k8s_cluster_name=\"$cluster\",      k8s_namespace_name=\"$namespace\"    },    \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.+)\"     )))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n  <h1>Services</h1>\n  <div style=\"display:flex; gap:8px; border-bottom: 1px solid #333;\">\n    <a href=\"/d/svc-overview?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:white; text-decoration:none; border-bottom: 1px solid #ff8833;\">\n        Overview\n    </a>\n    <a href=\"/d/svc-metric?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Metrics\n    </a>\n    <a href=\"/d/svc-log?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Logs\n    </a>                                                                            \n    <a href=\"/d/svc-trace?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Traces\n    </a>\n    <a href=\"/d/svc-trace-http?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        HTTP\n    </a>\n    <a href=\"/d/svc-trace-db?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        DB\n    </a>\n    <a href=\"/d/svc-trace-messaging?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Messaging\n    </a>\n    <a href=\"/d/svc-metric-jvm?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        JVM\n    </a>\n    <a href=\"/d/svc-metric-python?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Python\n    </a>\n    <a href=\"/d/svc-metric-nodejs?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        NodeJS\n    </a>\n  </div>\n</div>"
   }
  },
  {
   "title": "Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n    rate({\n        __name__=~\"http_server_request_duration_seconds_count|http_server_duration_milliseconds_count\",\n        service_name=\"$service\",\n        k8s_cluster_name=~\"$cluster\",\n        k8s_namespace_name=~\"$namespace\"\n    }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (service_name) (rate({\n    __name__=~\"http_server_request_duration_seconds_count|http_server_duration_milliseconds_count\",\n    service_name=\"$service\",\n    http_response_status_code=~\"5.*\",\n    k8s_cluster_name=~\"$cluster\",\n    k8s_namespace_name=~\"$namespace\"\n}[$__rate_interval]))\n/\nsum by (service_name) (rate({\n    __name__=~\"http_server_request_duration_seconds_count|http_server_duration_milliseconds_count\",\n    service_name=\"$service\",\n    k8s_cluster_name=~\"$cluster\",\n    k8s_namespace_name=~\"$namespace\"\n}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  histogram_quantile(0.95,\n    sum by (service_name, le, k8s_cluster_name, k8s_namespace_name) (\n      rate({\n        __name__=\"http_server_request_duration_seconds_bucket\",\n        service_name=~\"$service\",\n        k8s_cluster_name=~\"$cluster\",\n        k8s_namespace_name=~\"$namespace\"\n      }[$__rate_interval])\n    )\n  )\n)\nor\n(\n  histogram_quantile(0.95,\n    sum by (service_name, le, k8s_cluster_name, k8s_namespace_name) (\n      rate({\n        __name__=\"http_server_duration_milliseconds_bucket\",\n        service_name=~\"$service\",\n        k8s_cluster_name=~\"$cluster\",\n        k8s_namespace_name=~\"$namespace\"\n      }[$__rate_interval])\n    )\n  ) / 1000\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}