{
 "title": "Service Details > Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_labels,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_name=\"$cluster\"},k8s_namespace_name)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "query_result(sum by (service_name)(  label_replace(    kube_pod_labels {      label_app_kubernetes_io_name!=\"\",      k8s_cluster_name=\"$cluster\",      k8s_namespace_name=\"$namespace\"    },    \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.+)\"     )))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n  <h1>Services</h1>\n  <div style=\"display:flex; gap:8px; border-bottom: 1px solid #333;\">\n    <a href=\"/d/svc-overview?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:white; text-decoration:none; border-bottom: 1px solid #ff8833;\">\n        Overview\n    </a>\n    <a href=\"/d/svc-metric?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Metrics\n    </a>\n    <a href=\"/d/svc-log?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Logs\n    </a>                                                                            \n    <a href=\"/d/svc-trace?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Traces\n    </a>\n    <a href=\"/d/svc-trace-http?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        HTTP\n    </a>\n    <a href=\"/d/svc-trace-db?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        DB\n    </a>\n    <a href=\"/d/svc-trace-messaging?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Messaging\n    </a>\n    <a href=\"/d/svc-metric-jvm?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        JVM\n    </a>\n    <a href=\"/d/svc-metric-python?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Python\n    </a>\n    <a href=\"/d/svc-metric-nodejs?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        NodeJS\n    </a>\n  </div>\n</div>"
   }
  },
  {
   "title": "CPU 사용율(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate({\n    __name__=\"container_cpu_usage_seconds_total\",\n      k8s_cluster_name=\"$cluster\",\n      k8s_namespace_name=\"$namespace\",\n      k8s_pod_name!=\"\",\n      container!=\"\"\n  }[$__rate_interval])) by (k8s_pod_name)\n\n  /\n\n  sum({\n    __name__=\"kube_pod_container_resource_limits\",\n      resource=\"cpu\",\n      k8s_cluster_name=\"$cluster\",\n      k8s_namespace_name=\"$namespace\",\n      k8s_pod_name!=\"\"\n  }) by (k8s_pod_name)\n)\n* on (k8s_pod_name) group_left(label_app_kubernetes_io_name)\nlabel_replace ({\n  __name__=\"kube_pod_labels\",\n  k8s_cluster_name=\"$cluster\",\n  k8s_namespace_name=\"$namespace\",\n  k8s_pod_name!=\"\",\n  label_app_kubernetes_io_name=\"$service\"\n}, \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.*)\")",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory 사용율(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate({\n    __name__=\"container_memory_working_set_bytes\",\n      k8s_cluster_name=\"$cluster\",\n      k8s_namespace_name=\"$namespace\",\n      k8s_pod_name!=\"\"\n  }[$__rate_interval])) by (k8s_pod_name)\n  /\n  sum({\n  __name__=\"kube_pod_container_resource_limits\",\n    resource=\"memory\",\n    k8s_cluster_name=\"$cluster\",\n    k8s_namespace_name=\"$namespace\",\n    k8s_pod_name!=\"\"\n  }) by (k8s_pod_name)\n)\n\n* on (k8s_pod_name) group_left(label_app_kubernetes_io_name)\nlabel_replace ({\n  __name__=\"kube_pod_labels\",\n  k8s_cluster_name=\"$cluster\",\n  k8s_namespace_name=\"$namespace\",\n  k8s_pod_name!=\"\",\n  label_app_kubernetes_io_name=\"$service\"\n}, \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.*)\")\n",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Network 대역폭 수신량",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate({\n  __name__=\"container_network_receive_bytes_total\",\n    k8s_cluster_name=\"$cluster\",\n    k8s_namespace_name=\"$namespace\",\n    k8s_pod_name!=\"\"\n}[$__rate_interval])) by (k8s_pod_name)\n* on (k8s_pod_name) group_left(label_app_kubernetes_io_name)\nlabel_replace ({\n  __name__=\"kube_pod_labels\",\n  k8s_cluster_name=\"$cluster\",\n  k8s_namespace_name=\"$namespace\",\n  k8s_pod_name!=\"\",\n  label_app_kubernetes_io_name=\"$service\"\n}, \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.*)\")\n",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Network 대역폭 수신량",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate({\n  __name__=\"container_network_transmit_bytes_total\",\n    k8s_cluster_name=\"$cluster\",\n    k8s_namespace_name=\"$namespace\",\n    k8s_pod_name!=\"\"\n}[$__rate_interval])) by (k8s_pod_name)\n* on (k8s_pod_name) group_left(label_app_kubernetes_io_name)\nlabel_replace ({\n  __name__=\"kube_pod_labels\",\n  k8s_cluster_name=\"$cluster\",\n  k8s_namespace_name=\"$namespace\",\n  k8s_pod_name!=\"\",\n  label_app_kubernetes_io_name=\"$service\"\n}, \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.*)\")\n",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU 사용량 ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate({\n  __name__=\"container_cpu_usage_seconds_total\",\n    k8s_cluster_name=\"$cluster\",\n    k8s_namespace_name=\"$namespace\",\n    k8s_pod_name!=\"\",\n    container!=\"\"\n}[$__rate_interval])) by (k8s_pod_name)\n* on (k8s_pod_name) group_left(label_app_kubernetes_io_name)\nlabel_replace ({\n  __name__=\"kube_pod_labels\",\n  k8s_cluster_name=\"$cluster\",\n  k8s_namespace_name=\"$namespace\",\n  k8s_pod_name!=\"\",\n  label_app_kubernetes_io_name=\"$service\"\n}, \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.*)\")\n",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum({\n    __name__=\"kube_pod_container_resource_limits\",\n    resource=\"cpu\",\n    k8s_cluster_name=\"$cluster\",\n    k8s_namespace_name=\"$namespace\",\n    k8s_pod_name!=\"\"\n}) by (k8s_pod_name)\n\n* on (k8s_pod_name) group_left(label_app_kubernetes_io_name)\nlabel_replace ({\n  __name__=\"kube_pod_labels\",\n  k8s_cluster_name=\"$cluster\",\n  k8s_namespace_name=\"$namespace\",\n  k8s_pod_name!=\"\",\n  label_app_kubernetes_io_name=\"$service\"\n}, \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.*)\")\n",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory 사용량",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate({\n  __name__=\"container_memory_working_set_bytes\",\n    k8s_cluster_name=\"$cluster\",\n    k8s_namespace_name=\"$namespace\",\n    k8s_pod_name!=\"\",\n    container!=\"\"\n}[$__rate_interval])) by (k8s_pod_name)\n* on (k8s_pod_name) group_left(label_app_kubernetes_io_name)\nlabel_replace ({\n  __name__=\"kube_pod_labels\",\n  k8s_cluster_name=\"$cluster\",\n  k8s_namespace_name=\"$namespace\",\n  k8s_pod_name!=\"\",\n  label_app_kubernetes_io_name=\"$service\"\n}, \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.*)\")\n",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum({\n    __name__=\"kube_pod_container_resource_limits\",\n    resource=\"memory\",\n    k8s_cluster_name=\"$cluster\",\n    k8s_namespace_name=\"$namespace\",\n    k8s_pod_name!=\"\"\n}) by (k8s_pod_name)\n\n* on (k8s_pod_name) group_left(label_app_kubernetes_io_name)\nlabel_replace ({\n  __name__=\"kube_pod_labels\",\n  k8s_cluster_name=\"$cluster\",\n  k8s_namespace_name=\"$namespace\",\n  k8s_pod_name!=\"\",\n  label_app_kubernetes_io_name=\"$service\"\n}, \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.*)\")\n",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}