{
 "title": "Service Details > NodeJS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_labels,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_name=\"$cluster\"},k8s_namespace_name)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "query_result(sum by (service_name)(  label_replace(    kube_pod_labels {      label_app_kubernetes_io_name!=\"\",      k8s_cluster_name=\"$cluster\",      k8s_namespace_name=\"$namespace\"    },    \"service_name\", \"$1\", \"label_app_kubernetes_io_name\", \"(.+)\"     )))"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(sum by (k8s_pod_name, k8s_namespace_name, k8s_cluster_uid)(  kube_pod_info {    k8s_pod_name!=\"\",    k8s_namespace_name=\"$namespace\",    k8s_cluster_name=\"$cluster\"  })* on(k8s_pod_name) group_left(pod) kube_pod_labels {  label_app_kubernetes_io_name=\"$service\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n  <h1>Services</h1>\n  <div style=\"display:flex; gap:8px; border-bottom: 1px solid #333;\">\n    <a href=\"/d/svc-overview?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Overview\n    </a>\n    <a href=\"/d/svc-metric?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Metrics\n    </a>\n    <a href=\"/d/svc-log?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Logs\n    </a>                                                                            \n    <a href=\"/d/svc-trace?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Traces\n    </a>\n    <a href=\"/d/svc-trace-http?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        HTTP\n    </a>\n    <a href=\"/d/svc-trace-db?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        DB\n    </a>\n    <a href=\"/d/svc-trace-messaging?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Messaging\n    </a>\n    <a href=\"/d/svc-metric-jvm?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        JVM\n    </a>\n    <a href=\"/d/svc-metric-python?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Python\n    </a>\n    <a href=\"/d/svc-metric-nodejs?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:white; text-decoration:none; border-bottom: 1px solid #ff8833;\">\n        NodeJS\n    </a>\n  </div>\n</div>"
   }
  },
  {
   "title": "Heap Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum({\n        __name__=\"v8js_memory_heap_used_bytes\",\n        service_name=\"$service\"\n    })\n    /\n    sum({\n        __name__=\"v8js_memory_heap_limit_bytes\",\n        service_name=\"$service\"\n    })\n) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({\n    __name__=\"v8js_memory_heap_used_bytes\",\n    service_name=\"$service\"\n})",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "sum({\n    __name__=\"v8js_memory_heap_limit_bytes\",\n    service_name=\"$service\"\n})",
     "legendFormat": "Heap Limit"
    },
    {
     "expr": "sum({\n    __name__=\"v8js_memory_heap_space_physical_size_bytes\",\n    service_name=\"$service\"\n})",
     "legendFormat": "Physical Size"
    }
   ]
  },
  {
   "title": "Garbage Collection Metrics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate({\n    __name__=\"v8js_gc_duration_seconds_sum\",\n    service_name=\"$service\"\n}[5m])\n/\nrate({\n    __name__=\"v8js_gc_duration_seconds_count\",\n    service_name=\"$service\"\n}[5m])",
     "legendFormat": "Avg GC Duration"
    },
    {
     "expr": "rate({\n    __name__=\"v8js_gc_duration_seconds_count\",\n    service_name=\"$service\"\n}[5m])",
     "legendFormat": "GC Frequency"
    }
   ]
  },
  {
   "title": "Event Loop Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\n    __name__=\"nodejs_eventloop_utilization_ratio\",\n    service_name=\"$service\"\n}"
    }
   ]
  },
  {
   "title": "Event Loop Delay (CPU Pressure Indicator)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{\n    __name__=\"nodejs_eventloop_delay_p50_seconds\",\n    service_name=\"$service\"\n}",
     "legendFormat": "p50"
    },
    {
     "expr": "{\n    __name__=\"nodejs_eventloop_delay_p90_seconds\",\n    service_name=\"$service\"\n}",
     "legendFormat": "p90"
    },
    {
     "expr": "{\n    __name__=\"nodejs_eventloop_delay_p99_seconds\",\n    service_name=\"$service\"\n}",
     "legendFormat": "p99"
    },
    {
     "expr": "{\n    __name__=\"nodejs_eventloop_delay_max_seconds\",\n    service_name=\"$service\"\n}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}