{
 "title": "Service Details > HTTP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_labels,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_name=\"$cluster\"},k8s_namespace_name)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_name=\"$cluster\", k8s_namespace_name=\"$namespace\"},label_app_kubernetes_io_name)"
    }
   },
   {
    "name": "http_method",
    "label": "http_method",
    "query": {
     "query": "query_result(label_replace(  {    __name__=~\"http_server_request_duration_seconds_count|http_server_duration_milliseconds_count\",    k8s_cluster_name=\"$cluster\",    k8s_namespace_name=\"$namespace\",        service_name=\"$service\"  },  \"http_request_method\", \"$1\",\"http_method\", \"(.+)\" ))"
    }
   },
   {
    "name": "http_url",
    "label": "http_url",
    "query": {
     "query": "query_result(label_replace(  {    __name__=~\"http_server_request_duration_seconds_count|http_server_duration_milliseconds_count\",    k8s_cluster_name=\"$cluster\",    k8s_namespace_name=\"$namespace\",        service_name=\"$service\"  },  \"http_route\", \"$1\",\"http_target\", \"(.+)\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n  <h1>Services</h1>\n  <div style=\"display:flex; gap:8px; border-bottom: 1px solid #333;\">\n    <a href=\"/d/svc-overview?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Overview\n    </a>\n    <a href=\"/d/svc-metric?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Metrics\n    </a>\n    <a href=\"/d/svc-log?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Logs\n    </a>                                                                            \n    <a href=\"/d/svc-trace?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Traces\n    </a>\n    <a href=\"/d/svc-trace-http?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:white; text-decoration:none; border-bottom: 1px solid #ff8833;\">\n        HTTP\n    </a>\n    <a href=\"/d/svc-trace-db?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        DB\n    </a>\n    <a href=\"/d/svc-trace-messaging?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Messaging\n    </a>\n    <a href=\"/d/svc-metric-jvm?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        JVM\n    </a>\n    <a href=\"/d/svc-metric-python?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        Python\n    </a>\n    <a href=\"/d/svc-metric-nodejs?var-service=${service}&var-cluster=${cluster}&var-namespace=${namespace}\"\n        style=\"padding:6px 16px; color:#aaa; text-decoration:none;\">\n        NodeJS\n    </a>\n  </div>\n</div>"
   }
  },
  {
   "title": "요청수신 (by.URI)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (http_route) (\n  rate({\n  __name__=~\"http_server_request_duration_seconds_count|\",\n    service_name=~\"$service\",\n    http_route!~\"/actuator/health|/api/health\",\n    k8s_cluster_name=~\"$cluster\",\n    k8s_namespace_name=~\"$namespace\"\n  }[$__rate_interval])\n)\nor\nsum by (http_target) (\n  rate({\n    __name__=~\"http_server_duration_milliseconds_count\",\n    service_name=~\"$service\",\n    http_target!~\"/actuator/health|/api/health\",\n    k8s_cluster_name=~\"$cluster\",\n    k8s_namespace_name=~\"$namespace\"\n  }[$__rate_interval])\n)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP 요청 추적",
   "type": "table",
   "description": "HTTP 수신기반 추적\n- Duration 임계치: 1500ms",
   "gridPos": { "h": 18, "w": 19, "x": 5, "y": 3 },
   "targets": [
    {
     "filters": [
      {
       "id": "40e83fc2",
       "isCustomValue": false,
       "operator": "=~",
       "scope": "span",
       "tag": "http.request.method",
       "value": [ "$http_method" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service" ],
       "valueType": "string"
      },
      {
       "id": "3436a1be",
       "isCustomValue": false,
       "operator": "=~",
       "scope": "span",
       "tag": "http.route",
       "value": [ "$http_url" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": [ "GET /actuator/health" ],
       "valueType": "string"
      }
     ],
     "limit": 2000,
     "metricsQueryType": "range",
     "query": "{\n  resource.service.name=\"$service\"\n  && (span.http.request.method=~\"$http_method\" || span.http.method=~\"$http_method\")\n  && (span.http.route=~\"$http_url\" || span.http.target=~\"$http_url\")\n  && name!=\"GET /actuator/health\" && name!=\"GET /api/health\"\n} | select(span.http.response.status_code)",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "에러응답 (by.URI)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (http_route) ({\n  __name__=~\"http_server_request_duration_seconds_count\",\n  service_name=~\"$service\",\n  http_route!=\"/actuator/health\",\n  http_response_status_code=~\"5.*\",\n  k8s_cluster_name=~\"$cluster\",\n  k8s_namespace_name=~\"$namespace\"\n})",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "지연응답 (by.URI)",
   "type": "timeseries",
   "description": "응답시간 > 1500ms\n(임시로 10ms 설정함)",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (http_route) (\n  rate(http_server_request_duration_seconds_count{\n    service_name=~\"$service\",\n    http_route!=\"/actuator/health\",\n    k8s_cluster_name=~\"$cluster\",\n    k8s_namespace_name=~\"$namespace\"\n  }[5m])\n)\n-\nsum by (http_route) (\n  rate(http_server_request_duration_seconds_bucket{\n    service_name=~\"$service\",\n    le=\"0.01\", # 지연응답 기준(seconds)\n    http_route!=\"/actuator/health\",\n    k8s_cluster_name=~\"$cluster\",\n    k8s_namespace_name=~\"$namespace\"\n  }[5m])\n)",
     "legendFormat": "{{http_route}}"
    }
   ]
  }
 ]
}